### ISSUE TITLE
Add Comprehensive Type Hints

### ISSUE THREAD

**Issue by walterra** [walterra/doc2convo#7]
**Priority**: MEDIUM  
**Type**: Code Quality & Developer Experience  
**Effort**: 2-3 hours  

## Problem

The current codebase lacks type hints throughout, which results in:
- Poor IDE support and autocompletion
- Difficulty catching type-related bugs
- Reduced code maintainability
- No static type checking
- Poor documentation of function signatures

## Requirements

1. Add type hints to all functions and methods
2. Use modern typing features (Union → `|`, Optional → `| None`)
3. Create type aliases for common types
4. Configure mypy for strict type checking
5. Add py.typed marker for library distribution
6. Ensure compatibility with Python 3.8+

### Step 1: Create Type Definitions

Create `src/convo/types.py`:
```python
"""Type definitions for the convo package."""

from typing import List, Tuple, Dict, Any, Optional, Union, Protocol
from pathlib import Path

# Type aliases
SpeakerName = str
Text = str
Conversation = List[Tuple[SpeakerName, Text]]
AudioPath = Union[str, Path]
URL = str
HTMLContent = str

# Configuration types
ConfigDict = Dict[str, Any]
VoiceMapping = Dict[SpeakerName, str]

# Protocol for TTS engines
class TTSEngine(Protocol):
    """Protocol for text-to-speech engines."""
    
    def generate_audio(self, text: str, speaker: str, output_path: AudioPath) -> None:
        """Generate audio for given text."""
        ...
    
    def get_available_voices(self) -> List[str]:
        """Get list of available voices."""
        ...

# API response types
class APIResponse(Protocol):
    """Protocol for API responses."""
    content: List[Any]
    
class MessageContent(Protocol):
    """Protocol for message content."""
    text: str
```

### Step 2: Add Type Hints to Core Modules

Update `src/convo/validators.py`:
```python
"""Input validation and sanitization utilities."""

import re
from pathlib import Path
from urllib.parse import urlparse
from typing import List, Optional
import bleach

from .types import URL, SpeakerName, Text
from .exceptions import ValidationError

def validate_url(url: URL, allowed_schemes: Optional[List[str]] = None) -> URL:
    """Validate and normalize URL.
    
    Args:
        url: URL to validate
        allowed_schemes: List of allowed schemes (default: ['http', 'https'])
    
    Returns:
        Normalized URL
        
    Raises:
        ValidationError: If URL is invalid
    """
    # Implementation...
```

### Step 3: Configure mypy

Update `pyproject.toml` mypy section:
```toml
[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
show_error_codes = true
namespace_packages = true
mypy_path = "src"

[[tool.mypy.overrides]]
module = [
    "edge_tts.*",
    "pyttsx3.*",
    "pydub.*",
    "anthropic.*",
]
ignore_missing_imports = true
```

### Step 4: Add py.typed Marker

Create `src/convo/py.typed` (empty file):
```bash
touch src/convo/py.typed
```

## Acceptance Criteria

- [ ] All functions have type hints
- [ ] Type aliases are defined for common types  
- [ ] mypy passes with no errors on strict settings
- [ ] py.typed marker is included
- [ ] Protocol classes are defined for interfaces
- [ ] Generic types are used appropriately
- [ ] Backward compatibility with Python 3.8+
- [ ] IDE autocompletion works correctly

## Testing Type Hints

```bash
# Run mypy type checking
mypy src/

# Test with different Python versions
tox -e py38,py39,py310,py311,py312

# Check package typing in consuming code
python -c "import convo; reveal_type(convo.ConversationParser)"
```

## Type Checking in CI

Add to `.github/workflows/ci.yml`:
```yaml
- name: Type check with mypy
  run: |
    pip install mypy
    mypy src/
```

## Benefits

1. **Better IDE Support**: Autocompletion, error detection
2. **Early Bug Detection**: Catch type errors before runtime
3. **Self-Documenting Code**: Type hints serve as documentation
4. **Refactoring Safety**: Types help ensure changes don't break interfaces
5. **Library User Experience**: Better experience for package users

## References

- [Python Type Hints PEP 484](https://peps.python.org/pep-0484/)
- [typing module documentation](https://docs.python.org/3/library/typing.html)
- [mypy documentation](https://mypy.readthedocs.io/)
- [Protocols PEP 544](https://peps.python.org/pep-0544/)
